# Generated by Django 2.1.5 on 2019-02-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seqer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseCounter',
            new_name='Sequences',
        ),
    ]
