# Generated by Django 2.1.5 on 2019-02-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seqer', '0002_auto_20190208_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='title',
            field=models.CharField(default='seq', max_length=200),
        ),
    ]
